services:
  app:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./000-default.conf:/etc/apache2/sites-available/000-default.conf
    environment:
      - APP_ENV=local
      - DB_DATABASE=/database/imageDatabase.db
